name: CI & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "build-and-deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Run unit tests (vitest)
        run: NODE_ENV=test pnpm test -- --run

      - name: Lint & formatting check
        run: |
          pnpm lint:fix --max-warnings=0 || true
          pnpm prettier:write --check || true

      - name: Build project (Vite)
        run: pnpm run build

      - name: Copy index.html to 404.html for SPA routing
        run: cp packages/app/dist/index.html packages/app/dist/404.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/app/dist
          name: github-pages

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
